import "~/styles/globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { TopNav } from "./_components/page";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "T3 Setup",
  description: "Generated by Rodrigo",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex flex-col gap-4">
          <header>
            <TopNav />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
